### ISSUE TITLE
Scene Alias

### ISSUE THREAD

**Issue by cartobaldrica** [jakobzhao/storymap#1]
It would be nice if the official 'scene-name' didn't show in the navbar. Is there a way to create an alias?

**Comment by jakobzhao** [comment]
Issue fixed.

See example here: http://rawgit.com/jakobzhao/storymap/master/index.html

If the scene does not contain a name attribute, the program will show the object name of the scene, if it contains, it will show the name attribute.

This is how to use the name attribute in the JavaScript.
```javascript
    var scenes = {
        overview: {lat: 44, lng: -123.5, zoom: 7, position: 'fullpage', name: 'Cover Page'},
        portland: {lat: 45.5186089, lng: -122.7270297, zoom: 11, name: 'Portland'},
......
    }; 
```

**Comment by cartobaldrica** [comment]
The names look great! Unfortunately, the 'scrollScript' function no longer works. Clicking on the navbar icons doesn't move the page at all.
