### ISSUE TITLE
Top arrow?

### ISSUE THREAD

**Issue by cartobaldrica** [jakobzhao/storymap#2]
Right now there is only a bottom arrow on each page. I think a top arrow (to return to the previous section) would be useful as well.

Thank you!

**Comment by jakobzhao** [comment]
great! I will think about that.!

**Comment by jakobzhao** [comment]
Hi Gareth, the navbar function has been added.  see here: http://cdn.rawgit.com/jakobzhao/storymap/master/examples/navbar/index.html
