### ISSUE TITLE
Unrelated section tag breaks 'home button'

### ISSUE THREAD

**Issue by VictorVelarde** [jakobzhao/storymap#5]
Hi @jakobzhao, thx for your nice library!

Having used it recently in a little example, we were having problems with 'home button' not working fine. We checked the code and the problem is this function:

```js
$('.storymap-scroll-down').click(function () {
  var viewing = $(".viewing");
  if (viewing.data("scene") !== $("section:last").data("scene")) {
    if (nav.length !== 0) {
      window.scrollBy(0, viewing.offset().top + viewing.height() - $(window).scrollTop() - $('.storymap-navbar').height() - 10);
    } else {
      window.scrollBy(0, viewing.offset().top + viewing.height() - $(window).scrollTop() - 10);
    }
  } else {
    window.scrollTo(0, 0);
  }
}); 
```

As you can see, there is a DOM selector like `$("section:last").data("scene"))`, and in our web page we had another, unrelated 'section' tag (without any 'scene' attribute), so that broke the 'if' when returning undefined.

IMO it should be enough to just replace it with **`$("section[data-scene]:last").data('scene')`** to fix it.

Thx!

---
PD We were using https://cdn.rawgit.com/jakobzhao/storymap/master/dist/storymap.2.4.js

**Comment by jakobzhao** [comment]
bug fixed! Thank you so much @VictorVelarde

**Comment by VictorVelarde** [comment]
Thx @jakobzhao !!
